CREATE TABLE PRODUCT(
ID VARCHAR2(200),
NAME VARCHAR2(200),
CONTENT VARCHAR2(200),
PRICE VARCHAR2(200),
COMPANY VARCHAR2(200),
IMG VARCHAR2(200)
)

CREATE TABLE BOUNUS(
ENAME VARCHAR2(200),
JOB VARCHAR2(200),
SAL NUMBER(10,
0),
COMM NUMBER(10,
0)
)

CREATE TABLE orderlist(
	"no" varchar2(100),
	member_id varchar2(100),
	product_id varchar2(100),
	total_count varchar2(100)
)

CREATE TABLE depart(
	ID VARCHAR2(200),
	NAME VARCHAR2(200),
	instructor varchar2(100)
)

CREATE TABLE student(
	ID VARCHAR2(200),
	NAME VARCHAR2(200),
	tel varchar2(100),
	depart_id varchar2(100)
)

CREATE TABLE subject(
	ID VARCHAR2(200),
	title VARCHAR2(200),
	depart_id varchar2(100)
)

CREATE TABLE "HR"."BBS2" 
( "no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 

CREATE TABLE "HR"."BBS3" 
( "no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
) 

ALTER TABLE HR.BBS3 
ADD CONSTRAINT FK_MEMBER3
FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);

--1

CREATE TABLE depart2(
	ID VARCHAR2(200),
	NAME VARCHAR2(200),
	instructor varchar2(100),
	CONSTRAINT "depart_PK21" PRIMARY KEY (ID)
)

--2

CREATE TABLE "HR"."STUDENT2" 
   (	"ID" VARCHAR2(200), 
	"NAME" VARCHAR2(200), 
	"TEL" VARCHAR2(100), 
	"DEPART_ID" VARCHAR2(100)
   )

ALTER TABLE HR.STUDENT2
ADD CONSTRAINT STUDENT2_PK PRIMARY KEY (ID)
ENABLE;

ALTER TABLE HR.STUDENT2 
ADD CONSTRAINT FK_DEPART2 
FOREIGN KEY (DEPART_ID) REFERENCES HR.DEPART2(ID);

--테이블 복사

CREATE TABLE member22
AS SELECT * FROM "MEMBER" 

INSERT INTO MEMBER22 
VALUES ('banana','banana','banana','banana',sysdate)

INSERT INTO MEMBER22 
VALUES ('banana2','banana2','banana2','banana2',sysdate)

INSERT INTO MEMBER22 
VALUES ('banana3','banana3','banana3','banana3',sysdate)

INSERT INTO MEMBER22 
VALUES ('banana4','banana4','banana4','banana4',sysdate, 'aaa')

SELECT * FROM MEMBER22

INSERT INTO BBS3 
VALUES (bbs_id_seq.nextval,'happy','happy day','ice')

INSERT INTO BBS3 
VALUES (bbs_id_seq.nextval,'happy','happy day','ice')

SELECT *FROM BBS3

CREATE SEQUENCE pd_id_seq 
INCREMENT BY 1
START WITH 1

CREATE TABLE product3 (
	id number(38, 0),
	name varchar2(100)
)

INSERT INTO product3 
VALUES (pd_id_seq.nextval, 'shoes')

INSERT INTO product3 
VALUES (pd_id_seq.nextval, 'shoes1')

SELECT * FROM product3


--orderlist 3 을 만드세요 

CREATE TABLE ORDERLIST3 (
	id number(38, 0),
	title varchar2(100),
	price number(38, 0)
)

CREATE SEQUENCE ol_seq 
INCREMENT BY 1
START WITH 1

INSERT INTO ORDERLIST3
VALUES (ol_seq.nextval, 'shoes', 5000)

INSERT INTO ORDERLIST3
VALUES (ol_seq.nextval, 'ram', 30000)

INSERT INTO ORDERLIST3
VALUES (ol_seq.nextval, 'camera', 155000)

SELECT * FROM ORDERLIST3 o 

SELECT * FROM ORDERLIST3 o 
ORDER BY id

SELECT * FROM ORDERLIST3 o 
ORDER BY id DESC 

SELECT * FROM ORDERLIST3 o 
WHERE id >=3
ORDER BY id DESC 

CREATE TABLE DEPT
(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

CREATE TABLE EMP
(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE SALGRADE
(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY
(DEPTNO));

 

ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO));

 

ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO));

SELECT * FROM EMP e 

SELECT DISTINCT DEPTNO  FROM EMP --중복제거

SELECT ename, sal * 12 FROM EMP e 

SELECT ename, sal * 12 AS yearsal FROM EMP e 

SELECT * FROM emp
ORDER BY SAL DESC 

SELECT * FROM EMP e 
WHERE DEPTNO = 30
ORDER BY EMPNO DESC

SELECT * FROM EMP e 
WHERE NOT DEPTNO = 30
ORDER BY EMPNO DESC 

SELECT * FROM EMP e
WHERE sal>=3000

SELECT * FROM EMP e
WHERE sal !=3000

SELECT * FROM EMP e 
WHERE job IN('SALESMAN', 'MANAGER')
ORDER BY JOB 

SELECT * FROM EMP e 
WHERE job NOT IN('SALESMAN', 'MANAGER')
ORDER BY JOB

SELECT * FROM EMP e 
WHERE sal BETWEEN 2000 AND 3000
ORDER BY EMPNO 

SELECT * FROM EMP e 
WHERE ename LIKE '_L%' -- _한자리 공백 아무거나 % 나머지 아무거나 조건검색

SELECT * FROM EMP e 
WHERE ename NOT LIKE '_L%'

SELECT * FROM EMP e 
WHERE COMM IS NULL 

SELECT * FROM EMP e 
WHERE COMM IS NOT NULL 

CREATE TABLE dept_temp2
AS
SELECT * FROM DEPT d 

SELECT * FROM dept_temp2

UPDATE DEPT_TEMP2 
SET loc = 'SEOUL'

UPDATE DEPT_TEMP2 
SET DNAME = 'DATABASE', loc = 'BUSAN'
WHERE DEPTNO = 40

DELETE FROM DEPT_TEMP2 dt 
WHERE DNAME = 'SALES'

SELECT * FROM DEPT_TEMP2 dt 



--2

SELECT * FROM PRODUCT p 
ORDER BY price DESC 

--3

SELECT NAME , CONTENT , PRICE  FROM PRODUCT p 
ORDER BY COMPANY 

--4

SELECT DISTINCT  COMPANY  FROM PRODUCT p 

--5

SELECT PRICE *5
AS price5
FROM PRODUCT p 

--6

SELECT NAME ,COMPANY  FROM PRODUCT p 
WHERE price = 5000

--7

SELECT NAME ,PRICE ,COMPANY  FROM PRODUCT p 
WHERE price BETWEEN 3000 AND 6000

--8
SELECT COMPANY ,NAME  FROM PRODUCT p 
WHERE COMPANY != 'c100'

--9

SELECT NAME, PRICE  FROM PRODUCT 
WHERE COMPANY = 'c200' OR COMPANY='c100'

--10

SELECT * FROM PRODUCT p 
WHERE name LIKE '%4'

--11

SELECT * FROM PRODUCT p 
WHERE name LIKE '%food%'

--12

UPDATE PRODUCT  
SET CONTENT = '품절'
WHERE PRICE = 5000

--13

UPDATE PRODUCT  
SET IMG = '0.png', price=10000
WHERE id = '100' AND ID ='102'

--14

DELETE FROM PRODUCT p 
WHERE COMPANY ='c100'

--15

DELETE FROM PRODUCT p 